In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [ ]:
(train_x,train_y),(test_x,test_y) = boston_housing.load_data()

In [ ]:
print("train shape :",train_x.shape)
print("Test shape :",test_x.shape)
print("Actual Train Output",train_y.shape)
print("Actual Test Output",test_y.shape)


train shape : (404, 13)
Test shape : (102, 13)
Actual Train Output (404,)
Actual Test Output (102,)


In [ ]:
train_x

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [ ]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [ ]:
test_x[0]

array([ 18.0846,   0.    ,  18.1   ,   0.    ,   0.679 ,   6.434 ,
       100.    ,   1.8347,  24.    , 666.    ,  20.2   ,  27.25  ,
        29.05  ])

In [ ]:
train_y[0]

15.2

In [ ]:
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)

In [ ]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

In [ ]:
train_y[0]

15.2

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
def HousePricePredictionModel():
  model=Sequential()
  model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
  model.add(Dense(64,activation='relu'))
  model.add(Dense(32,activation='relu'))
  model.add(Dense(1))
  model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model


In [ ]:
import numpy as np
k=4
num_val_samples= len(train_x)
num_epochs = 100
all_scores = []

In [ ]:
model = HousePricePredictionModel()
history=model.fit(x=train_x,y=train_y,epochs= num_epochs,batch_size=1,verbose=1,validation_data=(test_x,test_y))

Epoch 1/100
404/404 [==============================] - 3s 4ms/step - loss: 132.5623 - mae: 8.2955 - val_loss: 70.3824 - val_mae: 6.0714
Epoch 2/100
404/404 [==============================] - 1s 3ms/step - loss: 69.3444 - mae: 5.8042 - val_loss: 59.1298 - val_mae: 5.6943
Epoch 3/100
404/404 [==============================] - 1s 2ms/step - loss: 62.4168 - mae: 5.4305 - val_loss: 56.1526 - val_mae: 5.5338
Epoch 4/100
404/404 [==============================] - 1s 2ms/step - loss: 60.3918 - mae: 5.3467 - val_loss: 54.5281 - val_mae: 5.5162
Epoch 5/100
404/404 [==============================] - 1s 2ms/step - loss: 59.6237 - mae: 5.2669 - val_loss: 57.3897 - val_mae: 5.4031
Epoch 6/100
404/404 [==============================] - 1s 2ms/step - loss: 57.4460 - mae: 5.1686 - val_loss: 55.8456 - val_mae: 5.7118
Epoch 7/100
404/404 [==============================] - 1s 2ms/step - loss: 55.6990 - mae: 5.0963 - val_loss: 50.9223 - val_mae: 5.2472
Epoch 8/100
404/404 [==============================] -

In [ ]:
## We will need to convert train and test data using pandas

In [ ]:
test = [[0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
        0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
        0.02988655, 0.04031725, 0.04298041]]
print("Actual Output: ", train_y[0])
print("Predicted Output: ", model.predict(test))

Actual Output:  15.2
1/1 [==============================] - 0s 48ms/step
Predicted Output:  [[11.71047]]
